version: "3.8"

services:
  tg_bot:
    image: alexk0valchuk/bwgcombat:tgbot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BACKEND_URL=${BACKEND_URL}
      - WEBAPP_URL=${WEBAPP_URL}
      - ADMIN_ID=${ADMIN_ID}
      - CHANNEL_ID=${CHANNEL_ID}
      - CHANNEL_URL=${CHANNEL_URL}
    depends_on:
      - frontend
      - backend
  frontend:
    image: alexk0valchuk/bwgcombat:frontend
    ports:
      - "3000:3000"
    env_file:
      - front.env
  backend:
    image: alexk0valchuk/bwgcombat:salobackend
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py seed_db &&
              uvicorn app.asgi:application --host 0.0.0.0 --port 8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - media:/app/media/
      - static:/app/staticfiles/
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
  ngrok_fe:
    image: ngrok/ngrok:latest
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok_fe.yml"
    volumes:
      - ./ngrok_fe.yml:/etc/ngrok_fe.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN_FE}
      - WEBAPP_URL=${WEBAPP_URL}
    ports:
      - 4040:4040
    depends_on:
      - frontend
  ngrok_be:
    image: ngrok/ngrok:latest
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok_be.yml"
    volumes:
      - ./ngrok_be.yml:/etc/ngrok_be.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN_BE}
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - 4041:4040
    depends_on:
      - backend
  redis:
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"

volumes:
    dev-db-data:
    media:
    static: